# endpoints: map payer name → index-API URL
endpoints:
  example_payer: "https://www.centene.com/content/dam/centene/Centene%20Corporate/json/DOCUMENT/2025-04-29_fidelis_index.json"

cpt_whitelist:
  - "99213"
  - "99214"
  - "70450"
  - "72148"

logging:
  level: "INFO"
