cpt_whitelist:
- '99213'
- '99214'
- '72148'
- '73721'
- '70450'
- 0202U
- 0240U
- 0241U
- '10005'
- '10006'
endpoints:
  bcbs_il: https://app0004702110a5prdnc868.blob.core.windows.net/toc/2025-06-21_Blue-Cross-and-Blue-Shield-of-Illinois_index.json
logging:
  level: INFO
  output_file: sample_data/etl_pipeline.log
  structured: true
output:
  local_directory: sample_data
  s3:
    bucket: ${S3_BUCKET}
    prefix: ${S3_PREFIX}
    region: ${AWS_DEFAULT_REGION}
payer_endpoints:
  bcbs_fl: https://d1hgtx7rrdl2cn.cloudfront.net/mrf/toc/FloridaBlue_Health-Insurance-Issuer_index.json
  bcbs_il: https://app0004702110a5prdnc868.blob.core.windows.net/toc/2025-06-21_Blue-Cross-and-Blue-Shield-of-Illinois_index.json
processing:
  batch_size: 1000
  file_types:
  - in_network_rates
  max_files_per_payer: 25
  max_records_per_file: 1000000
  min_accuracy_score: 0.7
  min_completeness_pct: 50.0
  parallel_workers: 1
versioning:
  processing_version: tic-etl-sample-v1.0
  retention_days: 7
  schema_version: v2.1.0-sample
